name: emoji_picker_flutter
description: A Flutter package that provides an Emoji picker widget with 1500+ emojis in 8 categories.
version: 2.3.0
homepage: https://github.com/Fintasys/emoji_picker_flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.1.3
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.fintasys.emoji_picker_flutter
        pluginClass: EmojiPickerFlutterPlugin
